name: bounce_events

profile: bounce

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  bounce_events:
    +schema: raw

models:
  bounce_events:
    # Materialize staging models as views, and marts as tables
    1_staging:
      +schema: stage_bounce
      +materialized: view
    2_marts:
      +schema: mart_bounce
      +materialized: table
